### ISSUE TITLE
Parse "_embedded" variable to gain access to featuredmedia.source_url

### ISSUE THREAD

**Issue by matejmosko** [ArunPrakashG/wordpress_client#51]
In wordpress rest api if I add ?_embed at the end of the request, wordpress includes some other information to json at __embedded. Most notable is complete information about wp:featuredmedia including link to featured image (wp:featuredmedia[0].source_url). This bypasses the need to install separate plugins on host wordpress to include featured media url in json (which I am not allowed to the in some cases). 

The

**Comment by ArunPrakashG** [comment]
Hi @matejmosko ,
Good to know, I think i could check on this key for the featured image property in the response model to include the url in the said key there.

**Comment by ArunPrakashG** [comment]
@matejmosko , I was just checking on the same and I found the resulting API response size has increased by almost 100KB.
Due to this, I have not included this by default. instead, you can fetch this from the raw response object which is now returned from the WordpressResponse like so:
```dart
final client = WordpressClient.initialize(
    baseUrl: baseUrl,
    bootstrapper: (bootstrapper) => bootstrapper.withDebugMode(true).build(),
  );

  final response = await client.posts.retrieve(
    RetrievePostRequest(
      id: 1,
    ),
  );

  response.map<void>(
    onSuccess: (response) {
      final featuredImageLink = castOrElse(
        response['_embedded']['wp:featuredmedia']['link'],
      );

      print(
        'Featured image link: $featuredImageLink',
      );
    },
    onFailure: (response) {
      print(response.error);
    },
  );
```

Note: castOrElse is an in-built helper method to cast to a type with optional parameters to transform the value or pass a default value incase the casting fails.

Try this out and let me know how it goes for you. it is now available on pub.dev. use 8.3.10 version.

**Comment by matejmosko** [comment]
Hi, thanks. Meantime found out I can force ListPostRequest to fetch _embedded this way

```dart
    final request =
        ListPostRequest(page: page, perPage: 20, extra: {"_embed": "wp:featuredmedia"}) 
```

And afterwards I access the value anywhere using extension on Post type:

```dart
extension FeaturedImage on Post{
  String featuredImageSourceUrl(){
      return this["_embedded"]["wp:featuredmedia"][0]["source_url"];
  }
}
```

But your solution for a single post works . Thank you very much for your work.

P.S. When I add value wp:featuredmedia to _embed, the size footprint is significately smaller (only 3KB for me)) I have found this out today after you pinpointed the size.

**Comment by matejmosko** [comment]
Thank you again. Already wrapped :).
